spring:
  application:
    name: demo-client1 # Spring 应用名

server:
  port: 18080 # 服务器端口。默认为 8080

eureka:
  client:
    register-with-eureka: true # 注册到 Eureka-Server，默认为 true
    fetch-registry: true # 从 Eureka-Server 获取注册表，默认为 true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ # Eureka-Server 地址
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 1 # 发送心跳间隔时间(发送续约间隔时间)，默认30秒
    lease-expiration-duration-in-seconds: 2 # 续约时间，默认90秒

